stages:
  - reports

bearer:
  stage: reports
  only:
    - main
  image:
    name: bearer/bearer
    entrypoint: [ "" ]
  script:
    - bearer scan . --diff --format gitlab-sast --output gl-sast-report.json
  artifacts:
    reports:
      sast: gl-sast-report.json

bearer_mr_check:
  stage: reports
  only:
    - merge_requests
  script:
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b /usr/local/bin
    - ./bearer scan --diff . --debug
